
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
# Install Terraform
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

# Initialize Terraform
- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(Pipeline.Workspace)'
    backendServiceArm: 'new2'
    backendAzureRmResourceGroupName: 'ap_rg1'
    backendAzureRmStorageAccountName: 'terraform524'
    backendAzureRmContainerName: 'container52'
    backendAzureRmKey: 'terraform.tfstate'

# Apply Terraform configuration
- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(Pipeline.Workspace)'
    environmentServiceNameAzureRM: 'new2'

# Publish the Terraform artifact
- task: PublishPipelineArtifact@1
  inputs:
    artifactName: 'terraform-artifact'
    targetPath: '$(System.DefaultWorkingDirectory)'

# Download the Terraform artifact
- task: DownloadPipelineArtifact@2
  inputs:
    artifactName: 'terraform-artifact'
    targetPath: '$(Pipeline.Workspace)'
